// Lifecycle tests: every expectation hand-computed, no fixtures generated by
// the code under test.
//
//   node --experimental-strip-types --import ./scripts/register-alias.mjs scripts/lifecycle-test.mjs
import { readLifecycle } from "../src/lib/lifecycle.ts";

let pass = 0, fail = 0;
const check = (name, ok, detail = "") => {
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}${detail ? " :: " + detail : ""}`);
  ok ? pass++ : fail++;
};
const near = (a, b, eps = 1e-6) => a != null && Math.abs(a - b) < eps;

const DAY = 86_400_000;
// Fixed clock so nothing here depends on when the suite runs.
const NOW = new Date("2026-08-08T12:00:00+04:00").getTime();
const day = (n) => new Date(`2026-08-${String(n).padStart(2, "0")}T00:00:00+04:00`).getTime();

/* ---- Trap 1: known-flat time counts toward the window ------------------- */
// The defining property of this data: snapshots are change points, so the
// stretch after the last one is time we LOOKED and saw nothing move.
{
  const series = [
    { at: day(1), views: 1000 },
    { at: day(2), views: 2000 },
  ];
  // Last change on the 2nd, but we polled through the 8th: 6 flat days.
  const r = readLifecycle({ series, observedUntil: day(8), postedAt: "2026-08-01", now: NOW });

  check("window runs to the last poll, not the last change",
    near(r.windowDays, 7), `got ${r.windowDays}`);
  check("flat time drags the daily rate down",
    near(r.dailyRate, 1000 / 7), `got ${r.dailyRate}`);

  // The bug this guards: dividing by the interval between the last two rows.
  check("rate is NOT the velocity it had on its last active day",
    !near(r.dailyRate, 1000), `naive answer would be 1000/day, got ${r.dailyRate.toFixed(1)}`);
}

/* ---- Trap 2: a mid-life window must not invent a half-life -------------- */
{
  // Published in January; we only started watching in August.
  const series = [
    { at: day(1), views: 500_000 },
    { at: day(8), views: 500_600 },
  ];
  const r = readLifecycle({ series, observedUntil: day(8), postedAt: "2026-01-15", now: NOW });

  check("a mid-life window reports partial coverage", r.coverage === "partial", r.coverage);
  check("and refuses to state a half-life", r.halfLifeDays === null, String(r.halfLifeDays));
  check("but still reports a real gain and rate",
    r.gainInWindow === 600 && near(r.dailyRate, 600 / 7));
}

/* ---- Momentum: the classifier that survives a partial window ------------ */
{
  const ageDays = (NOW - new Date("2026-02-08T00:00:00+04:00").getTime()) / DAY; // ~181

  // Earned 15% of its life in a 7-day window on a ~181-day-old post.
  // expected flat share = 7/181 = 0.0387; momentum = 0.15/0.0387 = 3.9
  const evergreen = readLifecycle({
    series: [{ at: day(1), views: 850_000 }, { at: day(8), views: 1_000_000 }],
    observedUntil: day(8), postedAt: "2026-02-08", now: NOW,
  });
  check("a post earning 15% of its life this week reads as rising",
    evergreen.shape === "rising", `${evergreen.shape} momentum=${evergreen.momentum?.toFixed(2)}`);
  check("recent share is gain over current total",
    near(evergreen.recentShare, 150_000 / 1_000_000));
  check("momentum compares that share to a flat accumulation",
    near(evergreen.momentum, (150_000 / 1_000_000) / (7 / ageDays), 1e-3),
    `got ${evergreen.momentum}`);

  // Same age, same window, almost nothing gained: the run is over.
  const faded = readLifecycle({
    series: [{ at: day(1), views: 999_900 }, { at: day(8), views: 1_000_000 }],
    observedUntil: day(8), postedAt: "2026-02-08", now: NOW,
  });
  check("a post earning 0.01% of its life this week reads as long tail",
    faded.shape === "tail", `${faded.shape} momentum=${faded.momentum?.toFixed(3)}`);

  // Right at its lifetime average.
  const steady = readLifecycle({
    series: [
      { at: day(1), views: 1_000_000 * (1 - 7 / ageDays) },
      { at: day(8), views: 1_000_000 },
    ],
    observedUntil: day(8), postedAt: "2026-02-08", now: NOW,
  });
  check("a post earning at exactly its lifetime average reads as steady",
    steady.shape === "steady", `${steady.shape} momentum=${steady.momentum?.toFixed(2)}`);
}

/* ---- Observed from birth ------------------------------------------------ */
{
  const series = [
    { at: day(2), views: 4_000 },
    { at: day(3), views: 7_000 },
    { at: day(5), views: 9_000 },
    { at: day(8), views: 10_000 },
  ];
  const r = readLifecycle({ series, observedUntil: day(8), postedAt: "2026-08-01", now: NOW });

  check("a post first seen a day after publication counts as from-birth",
    r.coverage === "from-birth", r.coverage);
  check("and a young one is still launching, not settled",
    r.shape === "launching", r.shape);

  // Half of 10,000 = 5,000, between day2 (4,000) and day3 (7,000):
  // fraction = (5000-4000)/(7000-4000) = 1/3 of that one-day step.
  // Crossing at day2 + 1/3 day; birth is day1 -> 1 + 1/3 days.
  check("half-life interpolates between the straddling readings",
    near(r.halfLifeDays, 1 + 1 / 3, 1e-6), `got ${r.halfLifeDays}`);
}

/* ---- Dormant vs unknown ------------------------------------------------- */
{
  const flat = readLifecycle({
    series: [{ at: day(1), views: 5_000 }, { at: day(8), views: 5_000 }],
    observedUntil: day(8), postedAt: "2026-01-01", now: NOW,
  });
  check("no gain across the whole window is dormant, not long-tail",
    flat.shape === "dormant", flat.shape);
  check("dormant still reports a real zero rate, not a gap", flat.dailyRate === 0);

  const single = readLifecycle({
    series: [{ at: day(1), views: 5_000 }],
    observedUntil: day(8), postedAt: "2026-01-01", now: NOW,
  });
  check("one reading cannot be classified", single.shape === "unknown", single.shape);
  check("and says so through coverage", single.coverage === "insufficient");
  check("one reading never fabricates a rate", single.dailyRate === 0);

  const none = readLifecycle({ series: [], observedUntil: day(8), postedAt: null, now: NOW });
  check("an empty series is unknown, not a crash", none.shape === "unknown");
}

/* ---- Tiny numbers are noise, not signal --------------------------------- */
// Straight from live data: a post with 8 lifetime views that gained 6 was
// being classified "steady" off a momentum of 1.18. A ratio on numbers that
// small says nothing, and printing it would invite decisions on nothing.
{
  const tiny = readLifecycle({
    series: [{ at: day(1), views: 2 }, { at: day(8), views: 8 }],
    observedUntil: day(8), postedAt: "2026-07-25", now: NOW,
  });
  check("a post with single-digit views is not classified",
    tiny.shape === "unknown", `${tiny.shape} momentum=${tiny.momentum?.toFixed(2)}`);
  check("but its real gain and rate are still reported",
    tiny.gainInWindow === 6 && near(tiny.dailyRate, 6 / 7));

  // The floor must not swallow the unambiguous case: zero gain is zero gain
  // however few views there are.
  const tinyFlat = readLifecycle({
    series: [{ at: day(1), views: 8 }, { at: day(8), views: 8 }],
    observedUntil: day(8), postedAt: "2026-07-25", now: NOW,
  });
  check("a tiny post that gained nothing is still dormant",
    tinyFlat.shape === "dormant", tinyFlat.shape);

  // Just over the floor, it classifies again.
  const enough = readLifecycle({
    series: [{ at: day(1), views: 40 }, { at: day(8), views: 120 }],
    observedUntil: day(8), postedAt: "2026-07-25", now: NOW,
  });
  check("a post above the floor classifies normally",
    enough.shape !== "unknown", enough.shape);
}

/* ---- Defensive edges ---------------------------------------------------- */
{
  // A stale sync stamp must never shorten the window below the real readings.
  const r = readLifecycle({
    series: [{ at: day(1), views: 100 }, { at: day(8), views: 200 }],
    observedUntil: day(3), postedAt: "2026-08-01", now: NOW,
  });
  check("an observedUntil behind the last reading cannot shrink the window",
    near(r.windowDays, 7), `got ${r.windowDays}`);

  // No publish date: rates are still real, momentum is not claimed.
  const undated = readLifecycle({
    series: [{ at: day(1), views: 100 }, { at: day(8), views: 800 }],
    observedUntil: day(8), postedAt: null, now: NOW,
  });
  check("without a publish date the rate still computes",
    near(undated.dailyRate, 100), `got ${undated.dailyRate}`);
  check("but momentum and shape are not invented",
    undated.momentum === null && undated.shape === "unknown",
    `${undated.shape} / ${undated.momentum}`);

  // A future-dated post must not produce a negative age.
  const future = readLifecycle({
    series: [{ at: day(1), views: 10 }, { at: day(8), views: 20 }],
    observedUntil: day(8), postedAt: "2027-01-01", now: NOW,
  });
  check("a future publish date yields no age rather than a negative one",
    future.ageDays === null, String(future.ageDays));

  // Platforms occasionally revise counts downward.
  const corrected = readLifecycle({
    series: [{ at: day(1), views: 1000 }, { at: day(8), views: 900 }],
    observedUntil: day(8), postedAt: "2026-01-01", now: NOW,
  });
  check("a downward correction reads as dormant, never a negative rate shape",
    corrected.shape === "dormant", corrected.shape);
}

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
